import { COLORS, SHADOWS, RADIUS, GLASS } from '@shared/config';

const styles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    ...GLASS.overlay,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 11000,
  },
  content: {
    background: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: '30px',
    width: '400px',
    maxWidth: '90%',
    boxShadow: SHADOWS.float,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    color: COLORS.charcoalBlue,
    fontWeight: '800',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    minWidth: '44px',
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  avatarPreview: {
    width: '80px',
    height: '80px',
    borderRadius: RADIUS.full,
    overflow: 'hidden',
    alignSelf: 'center',
    marginBottom: '10px',
    border: `2px solid ${COLORS.atomicTangerine}`,
    background: COLORS.surfaceGlass,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  avatarSkeleton: {
    width: '100%',
    height: '100%',
    borderRadius: RADIUS.full,
    background: COLORS.borderLight,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '800',
    color: COLORS.textSecondary,
    fontSize: '2rem',
  },
  label: {
    fontSize: '0.8rem',
    fontWeight: '700',
    color: COLORS.charcoalBlue,
    textTransform: 'uppercase',
  },
  input: {
    padding: '12px',
    borderRadius: RADIUS.sm,
    border: `1px solid ${COLORS.border}`,
    fontSize: '1rem',
  },
  saveBtn: {
    background: COLORS.atomicTangerine,
    color: 'white',
    padding: '14px',
    borderRadius: RADIUS.md,
    border: 'none',
    fontWeight: '800',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    gap: '8px',
    alignItems: 'center',
    minHeight: '44px',
  },
};

export default styles;
