import { COLORS, SHADOWS, RADIUS } from '@shared/config';

export const emptyStyles = {
  container: {
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: RADIUS.xl,
    padding: '32px 24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    textAlign: 'center',
    boxShadow: 'none',
    width: '100%',
    height: '100%',
    minHeight: 0,
    position: 'relative',
    overflow: 'hidden',
    minWidth: 0,
    boxSizing: 'border-box',
  },

  artWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '72px',
    height: '72px',
    backgroundColor: 'rgba(255, 107, 53, 0.06)',
    borderRadius: '50%',
    marginBottom: '4px',
    flexShrink: 0,
  },

  sparkleContainer: {
    position: 'absolute',
    top: '-6px',
    right: '-6px',
    backgroundColor: COLORS.surface,
    borderRadius: '50%',
    padding: '6px',
    display: 'flex',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },

  title: {
    margin: 0,
    fontSize: '1.15rem',
    fontWeight: '800',
    color: COLORS.charcoalBlue,
    letterSpacing: '-0.01em',
    lineHeight: 1.2,
  },

  text: {
    margin: 0,
    fontSize: '0.85rem',
    color: COLORS.textSecondary,
    lineHeight: 1.5,
    maxWidth: '240px',
    fontWeight: '500',
  },

  cta: {
    marginTop: '4px',
    background: `linear-gradient(135deg, ${COLORS.atomicTangerine}, #ff9a4d)`,
    color: 'white',
    border: 'none',
    borderRadius: RADIUS.full,
    padding: '10px 24px',
    fontSize: '0.88rem',
    fontWeight: '800',
    cursor: 'pointer',
    boxShadow: `0 6px 20px ${COLORS.atomicTangerine}30`,
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    flexShrink: 0,
  },
};
