import { COLORS, SHADOWS, RADIUS } from '@shared/config';
export const welcomeStyles = {
  pageHeader: (isMobile) => ({
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: isMobile ? '24px' : '28px',
    padding: '0px',
    position: 'relative',
    backgroundColor: 'transparent',
    borderRadius: 0,
    border: 'none',
    boxShadow: 'none',
  }),
  decorLayer: { position: 'absolute', inset: 0, pointerEvents: 'none', opacity: 0.5 },
  decorOrbA: { position: 'absolute', width: '140px', height: '140px', right: '-44px', top: '-56px', borderRadius: '999px', background: 'radial-gradient(circle, rgba(255,107,53,0.16) 0%, rgba(255,107,53,0) 72%)' },
  decorOrbB: { position: 'absolute', width: '120px', height: '120px', left: '-38px', bottom: '-60px', borderRadius: '999px', background: 'radial-gradient(circle, rgba(69,176,168,0.14) 0%, rgba(69,176,168,0) 74%)' },
  headerContent: { position: 'relative', zIndex: 1, display: 'flex', flexDirection: 'column', gap: '12px' },
  title: { margin: 0, fontSize: 'clamp(2rem, 3.5vw, 2.6rem)', fontWeight: '900', color: COLORS.charcoalBlue, lineHeight: 1.15, letterSpacing: '-0.02em' },
  subtitle: { margin: 0, marginTop: '4px', fontSize: 'clamp(0.95rem, 1.2vw, 1.1rem)', fontWeight: '500', color: COLORS.textSecondary, lineHeight: 1.4 },
  badgeRow: { display: 'inline-flex', alignItems: 'center', gap: '8px', marginTop: '8px', flexWrap: 'wrap', maxWidth: '100%' },
  badgeLevelButton: { display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '7px 14px', borderRadius: '999px', border: `1px solid ${COLORS.border}`, background: COLORS.surface, cursor: 'pointer', color: COLORS.charcoalBlue, fontWeight: 800, fontSize: '0.8rem', minHeight: '32px', transition: 'all 200ms ease-out' },
  badgeLevel: { fontSize: '0.8rem', fontWeight: '800', color: COLORS.atomicTangerine, display: 'flex', alignItems: 'center', gap: '4px' },
  badgeProgress: { fontSize: '0.7rem', fontWeight: '600', color: COLORS.textSecondary, opacity: 0.85 },
  statsSection: { position: 'relative', zIndex: 1, width: '100%' },
};