import { COLORS, SHADOWS, RADIUS } from '@shared/config';

export const welcomeStyles = {
  pageHeader: (isMobile) => ({
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: isMobile ? '10px' : '12px',
    padding: isMobile ? '16px' : '20px',
    position: 'relative',
    backgroundColor: 'transparent',
    borderRadius: 0,
    border: 'none',
    boxShadow: 'none',
  }),
  decorLayer: { position: 'absolute', inset: 0, pointerEvents: 'none', opacity: 0.5 },
  decorOrbA: { position: 'absolute', width: '140px', height: '140px', right: '-44px', top: '-56px', borderRadius: '999px', background: 'radial-gradient(circle, rgba(255,107,53,0.16) 0%, rgba(255,107,53,0) 72%)' },
  decorOrbB: { position: 'absolute', width: '120px', height: '120px', left: '-38px', bottom: '-60px', borderRadius: '999px', background: 'radial-gradient(circle, rgba(69,176,168,0.14) 0%, rgba(69,176,168,0) 74%)' },
  headerContent: { position: 'relative', zIndex: 1, display: 'flex', flexDirection: 'column', gap: '8px' },
  textStack: { display: 'flex', flexDirection: 'column', gap: '10px' },
  title: { margin: 0, fontSize: 'clamp(1.25rem, 2.2vw, 1.6rem)', fontWeight: '900', color: COLORS.charcoalBlue, lineHeight: 1.18, letterSpacing: '-0.02em' },
  subtitle: { margin: 0, marginTop: '0px', fontSize: 'clamp(0.88rem, 0.98vw, 0.95rem)', fontWeight: '500', color: COLORS.textSecondary, lineHeight: 1.5 },
  badgeRow: { display: 'inline-flex', alignItems: 'center', gap: '6px', marginTop: '4px', flexWrap: 'wrap', maxWidth: '100%' },
  badgeLevelButton: { display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '5px 12px', borderRadius: '999px', border: `1px solid ${COLORS.border}`, background: COLORS.surface, cursor: 'pointer', color: COLORS.charcoalBlue, fontWeight: 800, fontSize: '0.75rem', minHeight: '28px', transition: 'all 200ms ease-out' },
  badgeLevel: { fontSize: '0.75rem', fontWeight: '800', color: COLORS.atomicTangerine, display: 'flex', alignItems: 'center', gap: '3px' },
  badgeProgress: { fontSize: '0.7rem', fontWeight: '600', color: COLORS.textSecondary, opacity: 0.85 },
  statsSection: { position: 'relative', zIndex: 1, width: '100%' },

  /* ── Aspirational Empty State (New Traveler) ── */
  aspirationalBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '2px',
  },
  aspirationalText: {
    margin: 0,
    fontSize: 'clamp(0.95rem, 1.5vw, 1.08rem)',
    fontWeight: '600',
    color: COLORS.textSecondary,
    lineHeight: 1.5,
    letterSpacing: '-0.01em',
    fontStyle: 'italic',
    maxWidth: '380px',
  },
  aspirationalCta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    background: `linear-gradient(135deg, ${COLORS.atomicTangerine}, #ff9a4d)`,
    color: '#fff',
    border: 'none',
    borderRadius: '999px',
    fontSize: '0.82rem',
    fontWeight: '800',
    cursor: 'pointer',
    boxShadow: `0 6px 20px ${COLORS.atomicTangerine}35`,
    minHeight: '44px',
    width: 'fit-content',
    letterSpacing: '0.01em',
  },
};