import { COLORS, SHADOWS, RADIUS, TRANSITIONS, FONTS } from '@shared/config';

export const styles = {
  section: {
    backgroundColor: COLORS.background,
    padding: '0',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
  },

  card: (isMobile) => ({
    backgroundColor: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    boxShadow: SHADOWS.sm,
    borderRadius: '20px',
    padding: isMobile ? '16px 14px' : '20px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'relative',
    overflow: 'hidden',
  }),

  brandAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    background: `linear-gradient(90deg, ${COLORS.atomicTangerine}, ${COLORS.mutedTeal})`,
    opacity: 0.75,
    pointerEvents: 'none',
  },

  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '10px',
    flexWrap: 'wrap',
  },

  draftStatus: {
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: RADIUS.full,
    padding: '0 14px',
    background: COLORS.background,
    border: `1px solid ${COLORS.border}`,
    color: COLORS.textTertiary,
    fontSize: '0.72rem',
    fontWeight: 800,
    letterSpacing: '0.03em',
    textTransform: 'uppercase',
  },

  actionsRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },

  processingBadge: {
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: RADIUS.full,
    padding: '0 14px',
    background: `${COLORS.warning}14`,
    border: `1px solid ${COLORS.warning}40`,
    color: '#B45309',
    fontSize: '0.72rem',
    fontWeight: 700,
  },

  autoModeBtn: (isTituloAuto, isBusy) => ({
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: RADIUS.full,
    padding: '0 14px',
    background: isTituloAuto ? `${COLORS.danger}14` : COLORS.background,
    border: `1px solid ${isTituloAuto ? `${COLORS.danger}40` : COLORS.border}`,
    color: isTituloAuto ? COLORS.danger : COLORS.textSecondary,
    fontSize: '0.68rem',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    cursor: isBusy ? 'not-allowed' : 'pointer',
    opacity: isBusy ? 0.7 : 1,
    transition: TRANSITIONS.fast,
  }),

  content: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },

  titleInput: (isMobile) => ({
    width: '100%',
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: COLORS.textPrimary,
    fontFamily: FONTS.heading,
    fontSize: isMobile ? 'clamp(1.1rem, 4vw, 1.45rem)' : 'clamp(1.2rem, 3vw, 1.65rem)',
    fontWeight: 800,
    lineHeight: 1.2,
    letterSpacing: '-0.02em',
    minHeight: '52px',
    maxHeight: '52px',
    padding: '0',
    margin: '0',
    caretColor: COLORS.atomicTangerine,
    whiteSpace: 'normal',
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    display: '-webkit-box',
  }),

  flagsAndLocationRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },

  flagsStack: {
    display: 'flex',
    alignItems: 'center',
  },

  flagImage: (idx) => ({
    width: '30px',
    height: '30px',
    borderRadius: RADIUS.full,
    border: `2px solid ${COLORS.surface}`,
    boxShadow: SHADOWS.sm,
    background: COLORS.surface,
    objectFit: 'cover',
    display: 'inline-block',
    flexShrink: 0,
    marginLeft: idx > 0 ? '-9px' : '0',
    position: 'relative',
    zIndex: 10 - idx,
  }),

  flagEmoji: (idx) => ({
    width: '30px',
    height: '30px',
    borderRadius: RADIUS.full,
    border: `2px solid ${COLORS.surface}`,
    boxShadow: SHADOWS.sm,
    background: COLORS.surface,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
    lineHeight: 1,
    flexShrink: 0,
    marginLeft: idx > 0 ? '-9px' : '0',
    position: 'relative',
    zIndex: 10 - idx,
  }),

  locationText: {
    fontSize: '0.85rem',
    color: COLORS.textSecondary,
    fontWeight: 700,
  },
  titleHint: {
    fontSize: '0.75rem',
    color: COLORS.textTertiary,
    marginTop: '-4px',
    marginBottom: '8px',
    display: 'block',
  },

  tagsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
  },

  infoTag: {
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: RADIUS.sm,
    padding: '0 12px',
    background: COLORS.background,
    border: `1px solid ${COLORS.border}`,
    color: COLORS.textTertiary,
    fontSize: '0.78rem',
    fontWeight: 700,
  },

  infoTagIcon: {
    color: COLORS.textSecondary,
    flexShrink: 0,
  },
};
