import { COLORS, RADIUS, SHADOWS, TRANSITIONS } from '@shared/config';

export const styles = {
  shell: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
  },
  heroContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    alignItems: 'flex-start',
  },
  heroLabel: {
    fontSize: '0.65rem',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: COLORS.textSecondary,
    opacity: 0.7,
    margin: 0,
  },
  heroValue: {
    fontSize: 'clamp(1.8rem, 4vw, 2.5rem)',
    fontWeight: 900,
    color: COLORS.atomicTangerine,
    lineHeight: 0.9,
    letterSpacing: '-0.04em',
    margin: 0,
  },
  secondaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(clamp(100px, 12vw, 140px), 1fr))',
    gap: '12px 16px',
    width: '100%',
  },
  secondaryStat: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
  },
  value: {
    fontSize: 'clamp(1.3rem, 1.8vw, 1.6rem)',
    fontWeight: 900,
    color: COLORS.charcoalBlue,
    lineHeight: 1,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  label: {
    fontSize: '0.6rem',
    fontWeight: 600,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    margin: 0,
  },
  compactContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: '24px',
    width: '100%',
  },

  // HOME VARIANT: Horizontal layout with hero on left, secondary on right
  homeShell: (isMobile) => ({
    display: 'flex',
    flexDirection: isMobile ? 'column' : 'row',
    alignItems: isMobile ? 'flex-start' : 'center',
    gap: isMobile ? '12px' : '28px',
    width: '100%',
    justifyContent: isMobile ? 'flex-start' : 'space-between',
  }),
  homeHeroContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
    flexShrink: 0,
  },
  homeHeroLabel: {
    fontSize: '0.55rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: COLORS.textSecondary,
    opacity: 0.65,
    margin: 0,
  },
  homeHeroValue: {
    fontSize: 'clamp(2rem, 5.5vw, 3.5rem)',
    fontWeight: 900,
    color: COLORS.atomicTangerine,
    lineHeight: 0.85,
    letterSpacing: '-0.05em',
    margin: 0,
  },
  homeSecondaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '20px 28px',
    alignItems: 'start',
    flex: 1,
  },
  homeSecondaryStat: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    alignItems: 'flex-start',
  },

  // TRIPS VARIANT: Compact for TripCommandBar header
  tripsShell: {
    display: 'grid',
    gridTemplateColumns: '1fr repeat(3, 1fr)',
    alignItems: 'center',
    gap: '20px',
    width: '100%',
  },
  tripsHeroContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    alignItems: 'flex-start',
    borderRight: `1px solid ${COLORS.border}`,
    paddingRight: '20px',
  },
  tripsHeroLabel: {
    fontSize: '0.5rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: COLORS.textSecondary,
    opacity: 0.6,
    margin: 0,
  },
  tripsHeroValue: {
    fontSize: 'clamp(1.8rem, 3vw, 2.6rem)',
    fontWeight: 900,
    color: COLORS.atomicTangerine,
    lineHeight: 0.85,
    letterSpacing: '-0.04em',
    margin: 0,
  },
  tripsSecondaryGrid: {
    display: 'contents',
  },
  tripsSecondaryStat: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    alignItems: 'flex-start',
  },
  tripsValue: {
    fontSize: 'clamp(1.4rem, 2.2vw, 1.8rem)',
    fontWeight: 900,
    color: COLORS.charcoalBlue,
    lineHeight: 0.9,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  tripsLabel: {
    fontSize: '0.5rem',
    fontWeight: 700,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    margin: 0,
  },
};