import { COLORS, SHADOWS, RADIUS, GLASS, TRANSITIONS, FONTS, BUTTONS } from '@shared/config';

export const styles = {
  // ─── DESKTOP: Slide-over Panel ───
  desktopScrim: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...GLASS.overlay,
    zIndex: 2000,
    backdropFilter: 'blur(4px)',
  },
  desktopPanel: {
    position: 'fixed',
    top: 0,
    right: 0,
    width: 'min(480px, 60vw)',
    height: '100dvh',
    backgroundColor: COLORS.surface,
    zIndex: 2001,
    display: 'flex',
    flexDirection: 'column',
    boxShadow: SHADOWS.float,
    border: `1px solid ${COLORS.border}`,
    borderLeft: `1px solid ${COLORS.border}`,
  },

  // ─── MOBILE: Full-screen Sheet ───
  mobileScrim: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...GLASS.overlay,
    zIndex: 2000,
    backdropFilter: 'blur(4px)',
  },
  mobileSheet: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2001,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: COLORS.surface,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    boxShadow: SHADOWS.float,
  },

  // ─── SHARED: Sticky Top Action Bar ───
  stickyTopActionBar: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    padding: '12px 16px',
    borderBottom: `1px solid ${COLORS.border}`,
    backgroundColor: COLORS.surface,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  stickyBottomActionBar: {
    position: 'sticky',
    bottom: 0,
    zIndex: 12,
    borderTop: `1px solid ${COLORS.border}`,
    backgroundColor: COLORS.surface,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '10px',
    padding: '12px 16px',
    minHeight: '64px',
  },
  topBarSecondaryBtn: {
    background: COLORS.surface,
    color: COLORS.textTertiary,
    border: `1.5px solid ${COLORS.border}`,
    borderRadius: RADIUS.full,
    padding: '0 16px',
    minHeight: '44px',
    minWidth: '108px',
    fontSize: '0.88rem',
    fontWeight: '700',
    fontFamily: FONTS.heading,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    cursor: 'pointer',
    transition: TRANSITIONS.fast,
  },
  topBarPrimaryBtn: {
    ...BUTTONS.primary,
    borderRadius: RADIUS.full,
    padding: '0 20px',
    minHeight: '44px',
    minWidth: '116px',
    fontSize: '0.9rem',
    fontFamily: FONTS.heading,
    boxShadow: SHADOWS.md,
    letterSpacing: '0.01em',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },

  // ─── SHARED: Body (Scrollable) ───
  scrollableBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px 12px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },

  // ─── SECTION CONTAINERS ───
  sectionTitle: {
    fontSize: '0.85rem',
    fontWeight: '800',
    letterSpacing: '0.5px',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  sectionContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },

  // ─── FIELD GROUPS ───
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  fieldLabel: {
    fontSize: '0.8rem',
    fontWeight: '700',
    color: COLORS.charcoalBlue,
    letterSpacing: '0.3px',
  },
  fieldValue: {
    fontSize: '0.95rem',
    color: COLORS.charcoalBlue,
  },
};
