import { COLORS } from '../../theme';

export const styles = {
  gridContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gridAutoFlow: 'dense',
    gap: '25px',
    padding: '30px',
  },
  modalOverlay: { 
    position: 'fixed', 
    top: 0, 
    left: 0, 
    width: '100vw', 
    height: '100vh', 
    backgroundColor: 'rgba(15, 23, 42, 0.7)', 
    zIndex: 9999, 
    display: 'flex', 
    justifyContent: 'center', 
    alignItems: 'center',
    backdropFilter: 'blur(16px)', 
    WebkitBackdropFilter: 'blur(16px)',
    padding: '20px'
  },
  modalContent: { 
    backgroundColor: COLORS.linen, 
    width: '100%', 
    maxWidth: '850px', 
    maxHeight: '92vh', 
    borderRadius: '32px', 
    padding: '40px', 
    display: 'flex', 
    flexDirection: 'column', 
    overflowY: 'auto',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    border: '1px solid rgba(255, 255, 255, 0.5)',
  },

  // --- NUEVOS ESTILOS: HYBRID CANVAS (PANTALLA COMPLETA) ---
  expandedOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    backgroundColor: COLORS.linen,
    zIndex: 10000,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },
  expandedHeader: (foto) => ({
    height: '60vh',
    width: '100%',
    position: 'relative',
    backgroundImage: foto ? `url(${foto})` : 'none',
    backgroundColor: !foto ? COLORS.charcoalBlue : 'transparent',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    display: 'flex',
    alignItems: 'flex-end',
    padding: '60px',
    boxSizing: 'border-box',
  }),
  infoBar: {
    display: 'flex',
    justifyContent: 'center',
    gap: '40px',
    padding: '25px 50px',
    backgroundColor: '#fff',
    borderRadius: '24px',
    boxShadow: '0 15px 35px rgba(0,0,0,0.08)',
    width: 'fit-content',
    margin: '-45px auto 50px',
    zIndex: 10,
    border: '1px solid rgba(0,0,0,0.05)',
  },
  infoItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
  },
  hybridBody: {
    maxWidth: '1200px',
    width: '100%',
    margin: '0 auto',
    padding: '0 40px 100px',
    display: 'grid',
    gridTemplateColumns: '1.6fr 1fr',
    gap: '80px',
    boxSizing: 'border-box',
  },
  sectionTitle: {
    fontSize: '0.8rem',
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: '2px',
    color: COLORS.mutedTeal,
    marginBottom: '25px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  highlightCard: {
    backgroundColor: '#fff',
    padding: '28px',
    borderRadius: '24px',
    marginBottom: '25px',
    border: '1px solid rgba(0,0,0,0.03)',
    boxShadow: '0 4px 12px rgba(0,0,0,0.02)',
  },
  // --- FIN ESTILOS HYBRID CANVAS ---

  modalHeader: { 
    display: 'flex', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    marginBottom: '30px' 
  },
  closeBtn: { 
    background: 'rgba(44, 62, 80, 0.1)', 
    border: 'none', 
    borderRadius: '50%', 
    padding: '10px', 
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  formSection: {
    marginBottom: '30px',
    padding: '20px',
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px'
  },
  formRow: { 
    display: 'flex', 
    gap: '25px', 
    alignItems: 'flex-start'
  },
  inputGroup: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column'
  },
  label: { 
    display: 'flex', 
    alignItems: 'center', 
    gap: '6px', 
    fontSize: '0.75rem', 
    fontWeight: '800', 
    color: COLORS.charcoalBlue, 
    marginBottom: '8px', 
    textTransform: 'uppercase', 
    letterSpacing: '1px',
    opacity: 0.8
  },
  input: { 
    width: '100%', 
    border: '1px solid rgba(44, 62, 80, 0.1)', 
    borderRadius: '14px', 
    padding: '12px 16px', 
    fontSize: '0.95rem', 
    outline: 'none', 
    backgroundColor: '#fff', 
    color: COLORS.charcoalBlue,
    boxSizing: 'border-box'
  },
  uploadLabel: (foto) => ({ 
    display: 'flex', 
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%', 
    height: '220px',
    backgroundColor: foto ? 'transparent' : '#fff', 
    backgroundImage: foto ? `url(${foto})` : 'none',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    border: foto ? 'none' : `2px dashed ${COLORS.atomicTangerine}40`, 
    borderRadius: '24px', 
    cursor: 'pointer', 
    overflow: 'hidden',
    position: 'relative',
    transition: 'all 0.3s ease'
  }),
  textarea: { 
    width: '100%', 
    minHeight: '200px', 
    border: '1px solid rgba(44, 62, 80, 0.1)', 
    borderRadius: '18px', 
    padding: '20px', 
    fontSize: '1.1rem', 
    resize: 'none', 
    outline: 'none', 
    backgroundColor: '#fff', 
    color: COLORS.charcoalBlue, 
    lineHeight: '1.6',
    fontFamily: '"Georgia", serif',
    boxSizing: 'border-box'
  },
  saveBtn: { 
    backgroundColor: COLORS.atomicTangerine, 
    color: '#fff', 
    border: 'none', 
    padding: '16px 32px', 
    borderRadius: '16px', 
    fontWeight: '900', 
    cursor: 'pointer', 
    display: 'flex', 
    alignItems: 'center', 
    gap: '10px', 
    fontSize: '1rem'
  },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', position: 'relative', zIndex: 10 },
  actions: { display: 'flex', gap: '8px' },
  actionBtn: { background: 'white', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '6px', cursor: 'pointer', color: COLORS.charcoalBlue },
  btnNavFoto: { background: 'rgba(255,255,255,0.3)', border: '1px solid rgba(255,255,255,0.4)', borderRadius: '8px', padding: '6px', cursor: 'pointer', color: 'white', backdropFilter: 'blur(8px)' },
  fotoOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, background: 'linear-gradient(to bottom, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.4) 40%, rgba(0,0,0,0.85) 100%)', zIndex: 1 },
  fullWidthGlass: { background: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(15, 23, 42, 0.9) 100%)', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)', padding: '30px 20px 25px', width: '100%', boxSizing: 'border-box' },
  badge: { padding: '4px 10px', borderRadius: '8px', fontSize: '0.7rem', fontWeight: '900', textTransform: 'uppercase' }
};