import { COLORS, SHADOWS, RADIUS } from '@shared/config';

export const styles = {
  dashboardContainer: (isMobile) => ({
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: isMobile ? '8px' : '12px',
    padding: isMobile ? '12px 12px 0' : '16px 18px 0',
    height: '100%',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    boxSizing: 'border-box',
  }),

  welcomeContainer: {
    flexShrink: 0,
    width: '100%',
    overflow: 'visible',
  },

  mainGrid: (isMobile) => ({
    display: isMobile ? 'flex' : 'grid',
    gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, minmax(0, 1fr))',
    flexDirection: isMobile ? 'column' : undefined,
    gap: isMobile ? '10px' : '12px',
    alignItems: isMobile ? undefined : 'stretch',
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  }),
mapSection: {
  display: 'flex',
  flexDirection: 'column',
  gap: '6px',
  flex: 1,
  minWidth: 0,
  minHeight: 0,
  overflow: 'hidden',
  width: '100%',
  height: '100%',
  position: 'relative',
},
mapSectionTitle: {
  margin: 0,
  fontSize: '0.8rem',
  fontWeight: '800',
  color: COLORS.charcoalBlue,
  textTransform: 'uppercase',
  letterSpacing: '0.4px',
  lineHeight: 1,
  flex: '0 0 auto',
},

  mapCard: (isMobile) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    borderRadius: RADIUS.xl,
    overflow: 'hidden',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    boxShadow: SHADOWS.md,
    backgroundColor: COLORS.background,
    position: 'relative',
  }),

  mapErrorFallback: (isMobile) => ({
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: isMobile ? '160px' : '220px',
    display: 'flex',
    justifyContent: 'center',
    padding: '16px',
    overflow: 'hidden',
    color: COLORS.textPrimary,
    background: `linear-gradient(160deg, ${COLORS.background} 0%, ${COLORS.surface} 56%, #f1f5f9 100%)`,
    border: `1px solid ${COLORS.border}`,
    borderRadius: RADIUS.xl,
  }),

  mapErrorBackdrop: {
    position: 'absolute',
    inset: 0,
    filter: 'blur(0.2px)',
  },

  mapErrorGlowA: {
    position: 'absolute',
    width: '56%',
    aspectRatio: '1 / 1',
    top: '-22%',
    right: '-8%',
    borderRadius: '50%',
    background: `${COLORS.atomicTangerine}28`,
    filter: 'blur(18px)',
  },

  mapErrorGlowB: {
    position: 'absolute',
    width: '62%',
    aspectRatio: '1 / 1',
    left: '-22%',
    bottom: '-30%',
    borderRadius: '50%',
    background: `${COLORS.mutedTeal}30`,
    filter: 'blur(20px)',
  },

  mapErrorGrid: {
    position: 'absolute',
    inset: 0,
    opacity: 0.4,
    backgroundImage: `linear-gradient(${COLORS.border} 1px, transparent 1px), linear-gradient(90deg, ${COLORS.border} 1px, transparent 1px)`,
    backgroundSize: '36px 36px',
    maskImage: 'radial-gradient(circle at 60% 40%, black 30%, transparent 90%)',
  },

  mapErrorPanel: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    width: 'min(92%, 380px)',
    padding: '16px',
    textAlign: 'center',
    borderRadius: RADIUS.lg,
    border: `1px solid ${COLORS.border}`,
    background: 'rgba(255, 255, 255, 0.72)',
    backdropFilter: 'blur(8px)',
    boxShadow: SHADOWS.md,
  },

  mapErrorText: {
    margin: 0,
    fontSize: '0.9rem',
    fontWeight: 600,
    color: COLORS.textSecondary,
    maxWidth: '34ch',
  },

  mapRetryBtn: {
    border: `1px solid ${COLORS.atomicTangerine}55`,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.atomicTangerine,
    color: COLORS.surface,
    minHeight: '44px',
    padding: '10px 18px',
    fontSize: '0.86rem',
    fontWeight: 700,
    cursor: 'pointer',
    letterSpacing: '0.01em',
    boxShadow: `0 10px 20px ${COLORS.atomicTangerine}40`,
  },

  recentsContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: '6px',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    width: '100%',
  },

  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: 0,
    gap: '8px',
  },

  sectionTitle: {
    margin: 0,
    fontSize: '0.8rem',
    fontWeight: '800',
    color: COLORS.charcoalBlue,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    lineHeight: 1,
    minWidth: 0,
    flex: 1,
  },

  viewAllBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: '700',
    color: COLORS.atomicTangerine,
    padding: '6px 10px',
    minHeight: '36px',
    minWidth: 'auto',
    borderRadius: RADIUS.sm,
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },

  cardsList: (isMobile) => ({
    display: 'grid',
    gridTemplateColumns: isMobile
      ? 'repeat(auto-fit, minmax(min(160px, 100%), 1fr))'
      : '1fr',
    gridAutoRows: '1fr',
    alignItems: 'stretch',
    gap: isMobile ? '8px' : '8px',
    overflow: 'hidden',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
  }),

  dashboardErrorCard: {
    gridColumn: '1 / -1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    padding: '14px',
    borderRadius: RADIUS.lg,
    border: `1px solid ${COLORS.border}`,
    background: `linear-gradient(180deg, ${COLORS.surface} 0%, ${COLORS.background} 100%)`,
    boxShadow: SHADOWS.sm,
    minWidth: 0,
  },

  dashboardErrorText: {
    margin: 0,
    fontSize: '0.9rem',
    lineHeight: 1.4,
    fontWeight: 700,
    color: COLORS.textPrimary,
  },

  dashboardErrorHint: {
    margin: 0,
    fontSize: '0.8rem',
    lineHeight: 1.35,
    color: COLORS.textSecondary,
    overflowWrap: 'anywhere',
  },

};
